#!/usr/bin/env python3
"""Regenerate data_inline.js from the data/*.json files.
Run:  python build_inline.py
Edit the JSON in data/ then re-run this to update the site."""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, 'data')

def load(name):
    with open(os.path.join(DATA, name), encoding='utf-8') as f:
        return json.load(f)

def js(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2)

out = []
out.append('/* AUTO-GENERATED by build_inline.py — edit data/*.json then re-run */\n')

for letter in ['a', 'b', 'c', 'd']:
    out.append(f'const INLINE_{letter.upper()} = {js(load(letter + ".json"))};\n')

# Unit 2 has only four learning aims (A-D); E and F are unused.
out.append('const INLINE_E = null;')
out.append('const INLINE_F = null;\n')

out.append(f'const INLINE_FLASHCARDS = {js(load("flashcards.json"))};\n')
out.append(f'const INLINE_QUESTIONS = {js(load("questions.json"))};\n')
out.append(f'const INLINE_EXTENDED = {js(load("extended.json"))};\n')

with open(os.path.join(HERE, 'data_inline.js'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(out))

print('data_inline.js regenerated from data/*.json')
