#!/usr/bin/env python3
"""Regenerate data_inline.js from the data/<unit>/*.json files.
Run:  python build_inline.py
Edit the JSON under data/unit1 or data/unit2 then re-run this to update the site.

Output shape:
  const INLINE_UNITS = {
    "u1": { "sections": {"a": {...}, ...}, "flashcards": {...},
            "questions": {...}, "extended": [...] },
    "u2": { ... }
  };
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, 'data')

UNITS = {
    'u1': ['a', 'b', 'c', 'd', 'e', 'f'],
    'u2': ['a', 'b', 'c', 'd'],
}

FOLDER = {'u1': 'unit1', 'u2': 'unit2'}


def load(unit, name):
    path = os.path.join(DATA, FOLDER[unit], name + '.json')
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def build_unit(unit):
    return {
        'sections': {letter: load(unit, letter) for letter in UNITS[unit]},
        'flashcards': load(unit, 'flashcards'),
        'questions': load(unit, 'questions'),
        'extended': load(unit, 'extended'),
    }


payload = {unit: build_unit(unit) for unit in UNITS}

body = json.dumps(payload, ensure_ascii=False, indent=2)

out = (
    '/* AUTO-GENERATED by build_inline.py — edit data/<unit>/*.json then re-run */\n\n'
    'const INLINE_UNITS = ' + body + ';\n'
)

with open(os.path.join(HERE, 'data_inline.js'), 'w', encoding='utf-8') as f:
    f.write(out)

total = sum(len(payload[u]['flashcards']['cards']) for u in payload)
print('data_inline.js regenerated: %d units, %d flashcards total'
      % (len(payload), total))
